### ISSUE TITLE
说一个悲剧的事情

### ISSUE THREAD

**Issue by Macu1** [sky-big/RabbitMQ#2]
刚刚发现，rabbitmq默认依赖了ranch和lager。。。这让我万分沮丧，甚至开始怀疑人生

**Comment by huxb23** [comment]
你好，为什么依赖了ranch和lager，是个悲剧的事情？
本人用rabbitmq了，客户端事务发送到mq中，最近服务器经常假死，进程在，但是发不进去消息，正常也关闭不了

**Comment by sky-big** [comment]
从rabbit管理后台看看服务器和队列的状态对不对

**Comment by sky-big** [comment]
抓一下rabbit的监听端口，看是否有数据

**Comment by Macu1** [comment]
我记得旧版本的rabbitmq，网络部分至少是自己独有的，还有很多人写了很多blog来分析这个。but！！！现在依赖ranch了。。。让我觉得，好像socket部分，不用ranch，就是政治不正确的。。

**Comment by huxb23** [comment]
谢谢两位大神的回复，从界面的监控看，没用事务的发送是可以发送进去，queue的发送速率可以看到，但是queue的待消费数量不增加，消费速率为0，用事务发送的就一直在等getReply，感觉就是服务端收到了消息，但是在queue的某个处理一直卡着了，rabbitmq我们用了一年多没出问题，从6月开始出了4次了，而且每次出的服务器不一样，在数据量大的时候出现过，半夜数据量小的时候也出现过

**Comment by Macu1** [comment]
你们流量压力很大吗。。是不是consumer的设置有问题，需要reply却没进行reply什么的？我只是之前试用了一下rabbitmq，但是有一天测试感觉效率不行，我就重做了一个简单的跨node通信节点管理方案。。

**Comment by huxb23** [comment]
出问题的时候流量是100Mbps，平时高峰会达到300Mbps
跑着跑着没有规律就出现了，测试环境还模拟不出来。。。。

**Comment by sky-big** [comment]
出现这种问题，最好是看看配置什么的是否正确，是否有人测试或者什么的导致出现了问题

**Comment by huxb23** [comment]
跑了差不多一年没出过问题，也没动过，突然出现这个问题，没有人做测试，现在也重现不了，也不知道啥原因
