### ISSUE TITLE
linux平台如何编译和启动？

### ISSUE THREAD

**Issue by tanwen321** [sky-big/RabbitMQ#6]
在centos的RabbitMQ-master目录make编译，报这个错
make: *** No rule to make target 'ebin/rabbit_app.in', needed by 'ebin/rabbit.app'.  Stop.
我看ebin目录也生成了文件，可是怎么启动？？
用scripts的rabbitmq-server启动报错～～（报错信息有点长）
在erl -pa ebin用application启动也报错～～（报错信息有点长）
请问怎么弄的？

**Comment by sky-big** [comment]
这个测试环境目前只支持windows系统，目前没有计划支持linux，建议在windows启动这个环境学习，windows环境下你可以在每个节点上启动对应的observer，这个方便你去学习。
