### ISSUE TITLE
rabbitmq启动后的进程

### ISSUE THREAD

**Issue by chazex** [sky-big/RabbitMQ#7]
请教一个问题哈，我这里使用镜像方式，做了个三台机器的集群。
其中有一个队列中的消息体较大，一个可能几k到几十k，导致队列变成了flow状态。同时在服务段出现了一个新的进程，如下，数量很多，有两台机器是各90个，另外一台机器是5个。我想了解下这个进程是做啥的呢，为啥有一台这么少，另外两台那么多，感觉像是有异常，没找到相关的日志。

/opt/erl17.5/lib/erlang/erts-6.4/bin/beam.smp -B -- -root /opt/erl17.5/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5/ebin -noshell -noinput -hidden -boot start_clean -sasl errlog_type error -mnesia dir "/data/rabbitmq/mnesia/rabbit@s03" -s rabbit_control_main -nodename rabbit@s03 -extra list_queues -p / name

感谢支持，谢谢。

**Comment by sky-big** [comment]
进程名字叫什么呢？你给的这些信息我看不出来啊

**Comment by sky-big** [comment]
需要给出更详细的信息
